- hosts: type_openstack_compute_floatingip_associate_v2
  become: yes
  become_user: root
  vars:
    ansible_user: ubuntu
  tasks:
    - apt:
        name:
        - telnet
      retries: 3
      delay: 3
    - debug: msg="howdy"
