- hosts: type_openstack_compute_floatingip_associate_v2
  become: yes
  become_user: root
  vars:
    ansible_user: ubuntu
  tasks:
    - wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22
        search_regex: OpenSSH
        delay: 20
    - apt:
        name:
        - telnet
    - debug: msg="howdy"
